// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddRecipientsEmailController from "./add_recipients_email_controller"
application.register("add-recipients-email", AddRecipientsEmailController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)
