// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import RecipientsController from "./recipients_controller"
application.register("recipients", RecipientsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
